version: "3.9"

services:
  bot:
    build: .
    container_name: kyrgyz_bot
    restart: always
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./images:/app/images
